spring:
  redis:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    zero:
      password: 123456
      database: 0
      sentinel:
        master: mysentinel
        nodes: 192.168.2.45:26379,192.168.2.45:26380,192.168.2.45:26381
    one:
      password: 123456
      database: 1
      sentinel:
        master: mysentinel
        nodes: 192.168.2.45:26379,192.168.2.45:26380,192.168.2.45:26381




