spring:
  redis:

    jedis:
      pool:
        max-active: 10
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    zero:
      password: "123456"
      database: 0
      sentinel:
        master: mysentinel
        nodes: 192.168.2.45:26379,192.168.2.45:26380,192.168.2.45:26381
    one:
      password: "123456"
      database: 1
      sentinel:
        master: mysentinel
        nodes: 192.168.2.45:26379,192.168.2.45:26380,192.168.2.45:26381
    two:
      password: "123456"
      database: 2
      sentinel:
        master: mysentinel
        nodes: 192.168.2.45:26379,192.168.2.45:26380,192.168.2.45:26381
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          max-wait: -1ms
          min-idle: 0
    three:
      password: "123456"
      database: 3
      sentinel:
        master: mysentinel
        nodes: 192.168.2.45:26379,192.168.2.45:26380,192.168.2.45:26381
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          max-wait: -1ms
          min-idle: 0

    timeout: 6000ms
    password: 123456
    # 集群只支持1个db
    cluster:
      max-redirects: 3
      nodes:
        - 192.168.2.45:7006
        - 192.168.2.45:7001
        - 192.168.2.45:7002
        - 192.168.2.45:7003
        - 192.168.2.45:7004
        - 192.168.2.45:7005







