version: '2'
services:
  redis1:
    image: redis:6.0.9
    container_name: redis1
    ports:
      - 7379:6379
    volumes:
      - ./config/redis1.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis1:/data
      - ./logs/redis1:/logs
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
  redis2:
    image: redis:6.0.9
    container_name: redis2
    ports:
      - 7380:6379
    volumes:
      - ./config/redis2.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis2:/data
      - ./logs/redis2:/logs
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
  redis3:
    image: redis:6.0.9
    container_name: redis3
    ports:
      - 7381:6379
    volumes:
      - ./config/redis3.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis3:/data
      - ./logs/redis3:/logs
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
  redis_sentinel1:
    image: redis:6.0.9
    container_name: redis_sentinel1
    ports:
      - 27379:26379
    volumes:
      - ./config/sentinel1.conf:/usr/local/etc/redis/sentinel.conf
      - ./data/sentinel1:/data
      - ./logs/sentinel1:/logs
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    restart: always
  redis_sentinel2:
    image: redis:6.0.9
    container_name: redis_sentinel2
    ports:
      - 27380:26379
    volumes:
      - ./config/sentinel2.conf:/usr/local/etc/redis/sentinel.conf
      - ./data/sentinel2:/data
      - ./logs/sentinel2:/logs
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    restart: always
  redis_sentinel3:
    image: redis:6.0.9
    container_name: redis_sentinel3
    ports:
      - 27381:26379
    volumes:
      - ./config/sentinel3.conf:/usr/local/etc/redis/sentinel.conf
      - ./data/sentinel3:/data
      - ./logs/sentinel3:/logs
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    restart: always
